### ISSUE TITLE
connection issues on Ubuntu

### ISSUE THREAD

**Issue by viorels** [morganrallen/simple-sphero#2]
I'm trying to use your library on Ubuntu 15.04, I'm having trouble connecting and I would really appreciate some help!

$ hcitool scan
Scanning ...
    68:86:E7:05:7B:21   Sphero-GGG

$ sudo rfcomm bind hci0 68:86:E7:05:7B:21 && sudo chmod o+rw /dev/rfcomm0

At this point the sphero temporarly changes color to blue. When i try to connect with the library, on('error') returns a generic error like this: [Error: Cannot open /dev/rfcomm0]

Although the device seems to be there:
$ ls -la /dev/rfcomm0 
crw-rw-rw- 1 root dialout 216, 0 Sep 10 16:24 /dev/rfcomm0

Can you please give me some tips on how to debug this further? I'm stuck on this error and google does not help me at all ... Sphero is not popular enough yet ;)

**Comment by morganrallen** [comment]
I'm looking into this as I'm seeing similar results. In the meantime, try
using Bluetooth Manager and see if you can connect from there.

**Comment by viorels** [comment]
I've tried Bluetooth Manager and I've made some some progress. Now I get a permanent violet color on Sphero after pairing from blueman (instead of a temporary violet). I've added my user to dialout group so I can have write permissions on /dev/rfcomm0. Still, when I try the orb javascript library, connect throws this error:

$ node orbtest.js 
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot open /dev/rfcomm0

$ cat orbtest.js 
var sphero = require("sphero"),
    orb = sphero("/dev/rfcomm0");
orb.connect(function() {
  // roll Sphero forward
  orb.roll(150, 0);
});

**Comment by morganrallen** [comment]
Oh... it looks like also you are reporting this issue to the wrong repo, but both suffer a similar problem. Can you post a gist of your package.json and code?

**Comment by morganrallen** [comment]
OK, couple things that might work.

First try running this before `bind`.

```
hciconfig hci0 sspmode 1
```

This enables Simple Pairing Mode, which I believe means it won't ask for a pin.

Run `rfcomm release hci0` if `/dev/rfcomm0` exists before running `bind` again.

If you're still getting issues, run `release` again and try this...

```
rfcomm connect hci0 <addr>
```

If successful you should receive this.

```
Press CTRL-C for hangup
```

In another console try running your code again.

**Comment by viorels** [comment]
My mistake, this code was for https://github.com/orbotix/sphero.js
But indeed, I get a similar error with simple-sphero and spheron

**Comment by viorels** [comment]
Thanks for the tips. After following the instructions I get the same result as with Blueman applet, a violet/blue and apparently connected Sphero (2.0, is it supported?) ...  

$ sudo rfcomm connect hci0 68:86:E7:05:7B:21
Connected /dev/rfcomm0 to 68:86:E7:05:7B:21 on channel 1
Press CTRL-C for hangup

$ nodejs node_modules/simple-sphero/demo.js /dev/rfcomm0
an error occured
[Error: Cannot open /dev/rfcomm0]

$ ls -la /dev/rfcomm0
crw-rw---- 1 root dialout 216, 0 Sep 19 13:43 /dev/rfcomm0

Thanks for trying to help.
